var _tmr=_tmr||[];
(function(){function s(a,c,b){a.addEventListener?a.addEventListener(c,b,!1):a.attachEvent&&a.attachEvent("on"+c,b)}function z(a,c,b){a.removeEventListener?a.removeEventListener(c,b,!1):a.detachEvent&&a.detachEvent("on"+c,b)}function fa(a,c){for(var b=0;b<c.length;b++)if(c[b]==a)return!0;return!1}function U(a,c){var b,d;if(!a)return"";var e=typeof a;if("number"===e||"boolean"===e||"string"===e||a.nodeType||a===a.window)return"";e=[];if("[object Array]"===Object.prototype.toString.call(a)){b=0;for(d=
a.length;b<d;b++)ta(e,null,a[b],c);b="[";d="]"}else{for(b in a)a.hasOwnProperty(b)&&ta(e,b,a[b],c);b="{";d="}"}return!e.length?"":b+e.join(",")+d}function ta(a,c,b,d){var e=typeof b;if("string"===e)b='"'+b.replace(/[\"\']/g,"\\$&")+'"';else if(!("number"===e||"boolean"===e))if(b=d?"":U(b),!b.length)return;a.push((null===c?"":'"'+c+'":')+b)}function ua(a){var c="";try{var b=new Uint8Array(a);window.crypto.getRandomValues(b);for(var d=0;d<a;d++)c+=(b[d]%16).toString(16)}catch(e){c="";for(d=0;d<a;d++)b=
Math.floor(16*Math.random()),c+=b.toString(16)}return c}function t(){return(new Date).getTime()}function n(a,c){var b={data:c,raw:a,url:"https://top-fwz1.mail.ru"+a},d;"function"!==typeof v.sendBeacon?d=!1:(b.dataSplitter=";",d=V(b.data,b.dataSplitter),d=!0===v.sendBeacon(b.url,d));d||(void 0===c?(b.dataSplitter=";",b.open=Sa,b.connect=Ta,b.startListen=Ua,b.stopListen=Va,b.open(b),b.connect(b)):("function"===typeof f.XMLHttpRequest?(b.dataSplitter=";",b.open=Wa,b.connect=Xa,b.startListen=Ya,b.stopListen=
Za,b.open(b),b.connect(b),d=!0):d=!1,d||$a(b)))}function $a(a){var c=g.createElement("iframe"),b=g.createElement("div");b.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");b.appendChild(c);g.body.appendChild(b);try{var d=c.contentWindow.document,e=d.createElement("div"),p;for(p in a.data)if(a.data.hasOwnProperty(p)){var w=a.data[p],L=typeof w;if("string"===L||"number"===L){var q=d.createElement("input");
q.setAttribute("type","hidden");q.setAttribute("name",p);q.value=w;e.appendChild(q)}}var f=d.createElement("form");f.setAttribute("action",a.url);f.setAttribute("method",va);f.setAttribute("enctype",wa);f.appendChild(e);var h=d.createElement("div");h.appendChild(f);d.body.appendChild(h);var F=function(){try{z(c,"load",F),g.body.removeChild(b)}catch(a){k&&console.warn("[TopMailRu] Error#1.2",a)}};s(c,"load",F);f.submit()}catch(G){k&&console.warn("[TopMailRu] Error#1.3",G)}}function Wa(a){a._connection=
new f.XMLHttpRequest}function Xa(a){a._connection.open(va,a.url);a._connection.setRequestHeader("Content-Type",wa);a._connection.send(V(a.data,a.dataSplitter))}function Ya(a){s(a._connection,"load",a._onload);s(a._connection,"error",a._onerror)}function Za(a){z(a._connection,"load",a._onload);z(a._connection,"error",a._onerror)}function Sa(a){a._connection=new Image}function Ta(a){a._connection.src=a.url+V(a.data,a.dataSplitter)}function Ua(a){a._connection.onload=a._onload;a._connection.onerror=
a._onerror}function Va(a){a._connection.onload=null;a._connection.onerror=null}function V(a,c){var b=c||";",d="",e;for(e in a)if(a.hasOwnProperty(e)){var p=a[e],w=typeof p;if("string"===w||"number"===w)d+=b+escape(e)+"="+escape(p)}return d}function ga(a){return(a=g.cookie.match(RegExp("(?:^|; )"+a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,"\\$1")+"=([^;]*)")))?decodeURIComponent(a[1]):null}function M(a,c,b){b=b||{};var d=b.expires;"number"===typeof b.expires&&(d=new Date,d.setTime(d.getTime()+b.expires));
d&&d.toUTCString&&(d=d.toUTCString());b.expires=d;a=a+"="+encodeURIComponent(c);for(var e in b)if((c=b[e])||0===c)a+="; "+e,!0!==c&&(a+="="+c);g.cookie=a}function ab(){var a="tmr"+(""+Math.random()).slice(2);try{return H=f.localStorage||null,H.setItem(a,a),H.removeItem(a),!0}catch(c){return H=null,k&&console.warn("[TopMailRu] Error#1.4",c),!1}}function bb(){if(!W)return null;for(var a=u.hostname.split(".").reverse(),c,b=1,d=a.length;b<d;b++){c=a[0];for(var e=1;e<=b;e++)c=a[e]+"."+c;var e=""+t(),p=
{domain:c,path:"/",expires:3E5};try{M("tmr_tcdhn",e,p);var w=ga("tmr_tcdhn"),p=p||{};p.expires=-1;M("tmr_tcdhn","",p);if(w===e)return c}catch(f){k&&console.warn("[TopMailRu] Error#1.8",f)}}return null}function X(a,c){W&&M(a,c,xa);if(ha)try{H.setItem(a,c)}catch(b){k&&console.warn("[TopMailRu] Error#1.6",b)}}function ia(a){var c;if(!(c=W?ga(a):null)){var b;if(ha)a:{try{b=H.getItem(a);break a}catch(d){k&&console.warn("[TopMailRu] Error#1.5",d)}b=null}else b=null;c=b}return c}function ya(a){var c=";e="+
escape("detect");n(x(a,"/tracker",!1,!1)+c)}function za(a,c){if(a.length){var b=U(c);4096<b.length||n("/datalayer",{js:"13",id:a[0],e:b,sid:ja,ids:a.join(),ver:ka,_:Math.random()})}}function h(){}function N(a){a&&"object"===typeof a&&(!A&&"id"in a)&&(A=a.id)}function cb(a){return(a=!B?void 0:B[a])&&la?a-la:void 0}function Aa(){if(B){for(var a=0,c="domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),b=0;b<c.length;b++){var d=!B?void 0:
B[c[b]];if(0<d&&(d<a||0==a))a=d}return a?a:void 0}}function O(a){return a&&"object"===typeof a&&("id"in a&&a.id||A)}function x(a,c,b,d){X(ma,++I);var e="id"in a?a.id:A,p="url"in a?a.url:u.href,w="referrer"in a?a.referrer:g.referrer,L="title"in a?a.title:g.title,q;q=na;null===q&&(q=db());q=null!==q?q?1:0:null;var h="userid"in a?a.userid:y||0===y?y:void 0,l;l=[];A&&e!==A&&l.push("sec");"dataLayer"in f&&l.push("dl");C&&l.push(["ecom"].concat(C).join("-"));l=l.join(",");var F=f.screen,G;G=(new Date).getTimezoneOffset();
var m="";if(f.Intl)try{m=f.Intl.DateTimeFormat().resolvedOptions().timeZone||""}catch(n){k&&console.warn("[TopMailRu] Error#1.1",n)}G=G+"/"+m;a.start=Aa();c=c+"?js=13"+(e?";id="+escape(e):"")+(p?";u="+escape(p):"")+(w?";r="+escape(w):"")+(a.start?";st="+escape(a.start):"")+("gender"in a?";gender="+escape(a.gender):"")+("age"in a?";age="+escape(a.age):"")+("pid"in a?";pid="+escape(a.pid):"")+(void 0!==h?";userid="+escape(h):"")+(d&&L?";title="+encodeURIComponent(L):"")+(F?";s="+F.width+"*"+F.height:
"")+";vp=";e=d=0;g.documentElement&&(g.documentElement.clientWidth||g.documentElement.clientHeight)?(d=g.documentElement.clientWidth,e=g.documentElement.clientHeight):"number"==typeof f.innerWidth&&(d=f.innerWidth,e=f.innerHeight);c=c+(""+d+"*"+e)+";touch="+eb+";hds="+fb+";flash=";if(null===P)if(P="",v.plugins&&v.plugins["Shockwave Flash"])P=v.plugins["Shockwave Flash"].description.split(" ")[2];else if(f.ActiveXObject)try{var r=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),r=r.GetVariable("$version"),
r=r.split(" ")[1].split(",");P=r[0]+"."+r[1]}catch(s){k&&console.warn("[TopMailRu] Error#1.12",s)}r=c+P+";sid="+ja+";ver="+ka+";tz="+encodeURIComponent(G);if(b){if(!B||!oa)b="";else{b=[];b.push(oa.type);b.push(oa.redirectCount);b.push(la);for(c=0;c<Ba.length;c++)b.push(cb(Ba[c]));b=b.join("/")}b=";nt="+b}else b="";b=r+b+("device"in a?";device="+escape(a.device):"")+";ni=";if(!v||!v.connection)r="";else{r=v.connection;c=[];for(e=0;e<Ca.length;e++){d=r[Ca[e]];if(void 0!==d)switch(d){case !0:d=1;break;
case !1:d=0;break;default:d=(""+d).replace(/\//g,"_")}c.push(d)}r=c.join("/")}return b+r+("params"in a?";params="+escape(U(a.params,!1)):"")+(null!==q?";detect="+q:"")+(W||ha?";lvid="+escape([Q,t(),I,J].join(":")):"")+(l?";opts="+escape(l):"")+("version"in a?";appver="+escape(a.version):"")+";_="+Math.random()}function Da(a){a=";e="+escape("PVT/"+a);for(var c=0;c<m.length;c++)n(x(m[c],"/tracker",!1,!0)+a)}function gb(){na=!0;Ea(1);if(!Fa&&!R){R=!0;for(var a=0;a<m.length;a++)ya(m[a])}}function hb(){Ea(0);
na=!1}function db(){var a=ga(Ga);if(null===a)return null;a=a.split("|");if(2!==a.length)return null;var c=a[1],c=t()-c;if(0>c||c>Ha)return null;a=parseInt(a[0],10);return isNaN(a)?null:a}function Ea(a){var c=t();a=[a,c].join("|");M(Ga,a,{path:"/",expires:Ha})}function Y(){g.addEventListener?(z(g,"DOMContentLoaded",Y),_tmr.onready()):g.attachEvent&&"complete"===g.readyState&&(z(g,"readystatechange",Y),_tmr.onready())}function Ia(){z(f,"load",Ia);_tmr.onready();_tmr.onload()}function Z(){z(f,"unload",
Z);z(f,"beforeunload",Z);_tmr.unload()}if("[object Array]"===Object.prototype.toString.call(_tmr)){var f=window,v=navigator,g=document,u=location,S="string"===typeof u.hostname?u.hostname:"",$=-1!=S.search(/(^|\.)odnoklassniki\.ru$/)||-1!=S.search(/(^|\.)ok\.ru$/),aa=-1!=S.search(/(^|\.)vk\.com$/),ib=-1!=S.search(/(^|\.)lamoda\.ru$/),jb=-1!=S.search(/(^|\.)kommersant\.ru$/),kb="string"===typeof u.search&&-1!=u.search.search(/[?&]rb_clickid=/),k="string"===typeof u.search&&-1!=u.search.search(/[?&]tmr_debug=1(?:&|$)/),
Ja=$||aa||ib||jb,lb=!kb,mb=$||aa,nb=$||aa,Ka=$||aa,Fa=!1,va="POST",wa="application/x-www-form-urlencoded",W=!(0===u.hostname.search(/^(\d+.)+\d+$/g)||-1!==u.hostname.search(/:/g)),H=null,ha=ab(),xa={domain:bb(),path:"/",expires:287712E5};(function(){var a;if(a=g.cookie.match(RegExp("(?:^|; )(tmr_tcdhn\\d+)=([^;]*)","g"))){for(var c=[],b,d=0,e=a.length;d<e;d++)b=a[d],(b=b.match(/(?:^|; )(tmr_tcdhn\d+)=([^;]*)/))&&c.push(b.slice(1));a=c}else a=null;if(a){c=0;for(d=a.length;c<d;c++)e=a[c][0],b=xa||{},
b.expires=-1,M(e,"",b)}})();var R=!1,na=null,Ha=864E5,Ga="tmr_detect",ob=function(){function a(a,b){var d=g.createElement("div");d.setAttribute("class",String.fromCharCode(97,100,118,98,108,111,99,107,32,97,100,118,101,114,116,98,108,111,99,107,32,97,109,109,98,108,111,99,107,32,98,45,98,97,110,110,101,114,32,98,45,109,101,100,105,97,45,98,97,110,110,101,114,32,112,117,98,95,51,48,48,120,50,53,48,32,112,117,98,95,51,48,48,120,50,53,48,109,32,109,101,100,105,117,109,95,114,101,99,116,97,110,103,108,
101,95,51,48,48,95,50,53,48,32,112,117,98,95,55,50,56,120,57,48,32,108,101,97,100,101,114,98,111,97,114,100,95,55,50,56,95,57,48,32,119,105,100,101,95,115,107,121,115,99,114,97,112,101,114,95,49,54,48,95,54,48,48,32,119,105,100,101,95,115,107,121,115,99,114,97,112,101,114,95,49,54,48,120,54,48,48,32,116,101,120,116,45,97,100,32,116,101,120,116,65,100,32,116,101,120,116,95,97,100,32,116,101,120,116,95,97,100,115,32,116,101,120,116,45,97,100,115,32,116,101,120,116,45,97,100,45,108,105,110,107,115,32,
97,100,95,116,101,120,116,32,97,100,95,116,101,120,116,32,98,97,110,110,101,114,95,116,101,120,116,32,116,101,120,116,45,98,97,110,110,101,114,32,98,45,114,98,32,114,98,45,115,108,111,116,32,98,45,112,114,111,109,111,45,97,100,32,105,45,98,114,97,110,100,105,110,103,32,98,114,97,110,100,105,110,103,45,112,32,114,98,45,118,105,100,101,111,45,119,105,100,103,101,116,32,98,45,109,105,109,105,99,45,97,100,118,32,112,109,45,116,111,111,108,98,97,114,95,95,98,97,110,110,101,114,32,114,98,95,98,111,100,
121,32,115,116,105,99,107,121,45,115,112,114,105,110,103,115,32,97,100,118,95,115,108,111,116,95,49,32,98,97,110,110,101,114,95,50,52,48,32,98,108,111,99,107,95,115,104,97,114,101,32,97,99,116,105,111,110,45,45,115,104,97,114,101,32,115,104,97,114,101,108,105,115,116,32,106,115,45,98,97,110,110,101,114,32,100,105,114,101,99,116,32,112,99,45,109,105,109,105,99,32,116,103,98,45,98,97,110,110,101,114,32,121,97,100,105,114,101,99,116,32,106,115,45,112,114,111,109,111,45,112,111,112,117,112,32,109,45,
115,117,98,115,99,114,105,112,116,105,111,110,32,112,45,116,97,114,103,101,116,32,112,45,100,105,114,101,99,116,104,97,99,107,32,114,98,45,102,108,111,97,116,105,110,103,32,116,114,103,45,98,45,98,97,110,110,101,114,45,98,108,111,99,107));d.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");d.setAttribute("id","trg-b-banners-1");d.setAttribute("data-view","SlotView.mimic");this.bait=g.body.appendChild(d);
this.bait.offsetParent;this.bait.offsetHeight;this.bait.offsetLeft;this.bait.offsetTop;this.bait.offsetWidth;this.bait.clientHeight;this.bait.clientWidth;this.loopNumber=0;this.fnPositive=a||null;this.fnNegative=b||null;var e=this;setTimeout(function(){e._checkBait.call(e)},1)}a.prototype._checkBait=function(){if(R)this._stop();else{var a=!1;null!==g.body.getAttribute("abp")||null===this.bait.offsetParent||0==this.bait.offsetHeight||0==this.bait.offsetLeft||0==this.bait.offsetTop||0==this.bait.offsetWidth||
0==this.bait.clientHeight||0==this.bait.clientWidth?a=!0:void 0!==f.getComputedStyle&&(a=f.getComputedStyle(this.bait,null),a="none"==a.getPropertyValue("display")||"hidden"==a.getPropertyValue("visibility"));(!0===a||10<=++this.loopNumber)&&this._stop();var b;if(a&&this.fnPositive)try{b=this.fnPositive,b()}catch(d){k&&console.warn("[TopMailRu] Error#1.9",d)}else if(!a&&10>this.loopNumber){var e=this;setTimeout(function(){e._checkBait.call(e)},50*this.loopNumber)}else try{b=this.fnNegative,b()}catch(p){k&&
console.warn("[TopMailRu] Error#1.10",p)}}};a.prototype._stop=function(){try{g.body.removeChild(this.bait)}catch(a){k&&console.warn("[TopMailRu] Error#1.11",a)}};return function(c,b){new a(c,b)}}(),C=null,La=!1,pa=[],pb=[36383,2540645,3171181,3074137,2057653],Ma;(function(){function a(a){for(var c=[],f,g,h=0,l=a.length;h<l;h++)if(g=a[h]){f=null;if(g.ecommerce){g=g.ecommerce;f=!1;var k={},m=void 0;for(m in g)g.hasOwnProperty(m)&&b[m]&&(f=!0,k[m]=g[m]);f=f?k:null}else if("event"===g[0])if(k=d[g[1]],
g=g[2],!k||!g.items)f=null;else{f={};f[k]={products:g.items};var k=!1,m={},n=void 0;for(n in g)"items"!==n&&("currency"===n?f.currencyCode=g[n]:e[n]?(k=!0,m[e[n]]=g[n]):g[n]&&(k=!0,m[n]=g[n]));k&&(f.actionField=m)}f&&(c.push(f),pa.push(f))}if(c.length){a=0;for(h=c.length;a<h;a++)za(ba,c[a]);C||(C=[0,0]);C[0]+=c.length;h=a=0;for(l=c.length;h<l;h++)a+=U(c[h]).length;C[1]+=a}}function c(b){if((b=f[b])&&"function"===typeof b.push){a(b);var c=b.push;b.push=function(){var b=c.apply(this,arguments);a([].slice.call(arguments,
0));return b}}}var b={currencyCode:"currencyCode",detail:"detail",add:"add",remove:"remove",checkout:"checkout",purchase:"purchase",refund:"refund"},d={view_item:b.detail,add_to_cart:b.add,remove_from_cart:b.remove,begin_checkout:b.checkout,purchase:b.purchase,refund:b.refund},e={transaction_id:"id",value:"revenue"};Ma=function(){c("dataLayer");La=!0}})();var ka="60.3.0",qa=0,ca=0,ja=ua(16),y=null,da=0,ma="tmr_reqNum",I=ia(ma),I=null===I?0:parseInt(I,10);X(ma,I);var J=ia("tmr_lvid"),Q=ia("tmr_lvidTS");
if(null===J||-1===J.search(/^[0-9a-fA-F]+$/))J=ua(32);X("tmr_lvid",J);if(null===Q||-1===Q.search(/^\d+$/))Q=""+t();X("tmr_lvidTS",Q);var A=0,m=[],ra=[],ea=[],ba=[],eb="ontouchstart"in f||1<(v.maxTouchPoints||v.msMaxTouchPoints)?"1":"0",fb=f.devicePixelRatio||0,P=null,Na=f.performance||f.mozPerformance||f.msPerformance||f.webkitPerformance||{},B=Na.timing||{},oa=Na.navigation||{},Ba="unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),
la=!B?void 0:B.navigationStart,Ca="downlink downlinkMax effectiveType rtt saveData type".split(" "),D,sa;D=function(a,c,b){if(c&&"object"===typeof c){var d="id"in c&&c.id||A,e=b.title||null,g,f=sa(c,{params:b.required,fn:b.fn});if(f.missed.length)console.warn("[TopMailRu]"+(d?"["+d+"]":"")+" Error#1.14","Unspecified "+(1<f.missed.length&&f.missed.slice(0,-1).join(", ")+" and "||"")+f.missed.slice(-1)+" in "+a);else{var h=sa(c,{params:b.optional,fn:b.fn});g=[].concat(f.values).concat(h.values);f=[].concat(f.missed).concat(h.missed);
b.value&&(c="value"in c&&c.value,!0!==b.value&&(c=c||b.value),c?g.push("value: "+c):f.push("value"));b=g.length?"{ "+g.join(", ")+" }":"";g=f.length?"("+(1<f.length?f.slice(0,-1).join(", ")+" and "+f.slice(-1)+" are":f.slice(-1)+" is")+" empty)":"";d?console.info("[TopMailRu]["+d+"]: "+(e||a)+" "+b+" "+g):console.warn("[TopMailRu] Error#1.15","Undefined counter ID of "+a+" "+b)}}else console.warn("[TopMailRu][]["+a+"] Error#1.13")};sa=function(a,c){var b=[],d=[],e,f,g;if(c.params)for(e in c.params)if(c.params.hasOwnProperty(e)&&
!1!==c.params[e])if(f=e in a&&a[e],!0!==c.params[e]&&(f=f||c.params[e]),f)try{g=c.fn?c.fn:null,b.push(e+': "'+(g?g(e,f):f)+'"')}catch(h){console.warn("[TopMailRu] Error#1.16",h)}else d&&d.push(e);return{values:b,missed:d}};h.prototype.callbackOnReady=function(a){k&&D("onReady",a,{title:"OnReady callback"});a&&"object"===typeof a&&"function"===typeof a.callback&&a.callback.call(a.context||null)};h.prototype.pageView=function(a){N(a);if(a&&("object"===typeof a&&a.id)&&(5>ra.length&&!fa(a.id,ra)&&(ra.push(a.id),
!1!==a.beat&&ea.push(a.id),m.push(a),R&&ya(a)),5>ba.length&&!fa(a.id,ba)&&(!0===a.ecom||fa(a.id,pb)))){ba.push(a.id);var c=[a.id];if(La)for(var b=0,d=pa.length;b<d;b++)za(c,pa[b])}k&&D("pageView",a,{title:"Page view",optional:{url:u.href}});O(a)&&(n(x(a,"/counter",!1,!0)),ca=t())};h.prototype.reachGoal=function(a){N(a);k&&D("reachGoal",a,{title:"Reach goal",value:!0,required:{goal:!0}});if(O(a)&&"goal"in a&&a.goal){var c="";"value"in a&&a.value&&(c=parseInt(a.value)||"");n(x(a,"/tracker",!1,!0)+(";e="+
escape("RG:"+c+"/"+a.goal)))}};h.prototype.itemView=function(a){k&&D("itemView",a,{title:"Item view",optional:{list:!0,pagetype:!0,productid:!0,totalvalue:!0},fn:function(a,b){return(""+b).replace(/;/g," ")}});if(O(a)){var c=a.list||"",b=a.productid||"",d=a.pagetype||"",e=a.totalvalue||0;(new Image).src="https://ad.mail.ru/retarget/?counter="+(a.id||A)+"&list="+c+"&productid="+b+"&pagetype="+d+"&totalvalue="+e+"&_="+Math.random();c="IV:"+e+"/"+(""+c).replace(/;/g," ")+";"+(""+b).replace(/;/g," ")+
";"+(""+d).replace(/;/g," ");n(x(a,"/tracker",!1,!1)+(";e="+escape(c)))}};h.prototype.sendEvent=function(a){N(a);k&&D("sendEvent",a,{title:"Send event",value:!0,required:{category:!0,action:!0},optional:{label:!0},fn:function(a,b){return(""+b).substr(0,300).replace(/;/g," ")}});if(O(a)&&"category"in a&&a.category&&"action"in a&&a.action){var c=(""+a.category).substr(0,300),b=(""+a.action).substr(0,300),d="";"label"in a&&a.label&&(d=(""+a.label).substr(0,300));var e="";"value"in a&&a.value&&(e=parseInt(a.value)||
"");c="CE:"+e+"/"+(""+c).replace(/;/g," ")+";"+(""+b).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");n(x(a,"/tracker",!1,!1)+(";e="+escape(c)))}};h.prototype.setUserID=function(a){if(null===a||!1===a||void 0===a)this.deleteUserID();else{var c=typeof a;"number"!==c&&"string"!==c?k&&console.warn("[TopMailRu] Error#1.17","Invalid user ID in setUserID"):(y=a,k&&console.info("[TopMailRu]: Global user ID = "+y))}};h.prototype.getUserID=function(){return y||0===y?y:void 0};h.prototype.deleteUserID=function(){y=
null;k&&console.info("[TopMailRu]: Reset global user ID to null")};h.prototype.getClientID=function(){var a=J;return a||0===a?a:void 0};h.prototype._MT_event=function(a,c,b){N(a);k&&D(c,a,{title:b});O(a)&&n(x(a,"/tracker",!1,!0)+(";e="+escape("MT:/"+c)))};h.prototype.miniAppEvent=function(a){this._MT_event(a,"miniAppEvent","VK Mini App Event")};h.prototype.processEvent=function(a,c){if(a&&"object"===typeof a)if("type"in a){if("onready"===a.type){if(c&&0>c)return;this.callbackOnReady(a)}else if(c&&
0<c)return;switch(a.type){case "pageView":this.pageView(a);break;case "reachGoal":this.reachGoal(a);break;case "itemView":this.itemView(a);break;case "sendEvent":this.sendEvent(a);break;case "setUserID":"userid"in a&&this.setUserID(a.userid);break;case "deleteUserID":this.deleteUserID();break;case "miniAppEvent":this.miniAppEvent(a)}}else k&&console.warn("[TopMailRu] Error#1.19","Unspecified type of push event");else k&&console.warn("[TopMailRu] Error#1.18","Invalid push event")};h.prototype.push=
function(a){for(var c=0,b=arguments.length;c<b;c++)this.processEvent(arguments[c])};var Oa=!1;h.prototype.onready=function(){Oa||(Oa=!0,!Fa&&!R&&ob(gb,hb),Ma())};var Pa=!1;h.prototype.onload=function(){if(!Pa){Pa=!0;da=t();if(!nb&&0<m.length){for(var a=";e="+escape("RT/load")+";et="+da,c=0;c<m.length;c++)n(x(m[c],"/tracker",!0,!1)+a);ca=da}lb||setTimeout(function(){Da(2)},2E3);mb||setTimeout(function(){Da(15)},15E3)}};h.prototype.beat=function(){if(!Ja&&qa){var a=t();if(!(12E4<a-qa)){if(12E4<a-ca)for(var c=
";e="+escape("RT/resend")+";et="+da,b=0;b<m.length;b++)!1!==m[b].beat&&n(x(m[b],"/tracker",!1,!0)+c);else 0<ea.length&&n("/tracker?"+V({js:"13",id:ea[0],e:"RT/beat",sid:ja,ids:ea.join(),ver:ka,_:Math.random()},";"));ca=a}}};var Qa=!1;h.prototype.unload=function(){if(!Qa&&(Qa=!0,!Ka)){var a;a=(a=Aa())?t()-a:void 0;a=";e="+escape("RT/unload")+";et="+t()+(a?";pvt="+escape(a):"");for(var c=0;c<m.length;c++)n(x(m[c],"/tracker",!1,!1)+a)}};h.prototype.activity=function(a){qa=t()};var K=_tmr;_tmr=new h;
for(var l=0,T=K.length,E;l<T;l++)(E=K[l])&&"object"===typeof E&&N(E);l=0;for(T=K.length;l<T;l++)E=K[l],_tmr.processEvent(E,1);l=0;for(T=K.length;l<T;l++)E=K[l],_tmr.processEvent(E,-1);if("complete"===g.readyState||"loading"!==g.readyState&&!g.documentElement.doScroll)_tmr.onready();else g.addEventListener?s(g,"DOMContentLoaded",Y):g.attachEvent&&s(g,"readystatechange",Y);if("complete"===g.readyState)_tmr.onload();else s(f,"load",Ia);Ka||(s(f,"unload",Z),s(f,"beforeunload",Z));if(!Ja){setInterval(function(){_tmr.beat()},
6E4);try{for(var Ra="scroll gesturechange touchmove mousedown mousemove mouseup touch".split(" "),qb=function(a){s(g,a,function(){_tmr.activity(a)})},l=0;l<Ra.length;l++)qb(Ra[l]);s(f,"scroll",function(){_tmr.activity("scallback")})}catch(rb){k&&console.warn("[TopMailRu] Error#1.20",rb)}}}})();
